baseURL = 'https://www.laneljc.cn'
languageCode = 'zh-CN'
title = "Lane's blog"
theme = 'maverick'

[permalinks]
  pages = "/:slug"

[params]
  logo = "https://laneljc-1321736255.cos.ap-nanjing.myqcloud.com/pic/%25E5%25A4%25B4%25E5%2583%258F3.png"
  description = "A minimal hugo theme focus on content"
  author = 'Lane'
  items = 10

  [params.comments]
    enabled = true
    githubRepo = 'Lane0218/myblog'
    theme = 'github-light'


[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Post"
    url = "/posts/"
    weight = -200

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
